package test {
    struct Person {
        String name;
        i32 birth_year;
    }

    exception TestException {
        i32 i;
    }

    interface Echo {
        String echo (String msg);
        String concat (List<String> msgs);
        void touchmenot () throws TestException;
    }
}
