package test {
    exception TestException {
        i32 i;
    }

    interface EchoCallback {
        async call (String msg);
    }

    interface Echo {
        String echo (String msg);
        String concat (List<String> msgs);
        void touchmenot () throws TestException;
        void recursiveEcho (String msg, EchoCallback cb);
    }
}
